In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from keras.datasets import fashion_mnist


C:\Users\abdo\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\abdo\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\abdo\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\abdo\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:522: FutureWarning: Passing (

In [3]:
h=tf.constant('hellow')
sess=tf.Session()
sess.run(h)

b'hellow'

In [6]:
with tf.Session() as sess:
    y=sess.run(h)

In [8]:
f=tf.fill((4,4),5)
sess=tf.Session()
sess.run(f)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
f=tf.ones((4,4))
sess.run(f)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [11]:
var=tf.Variable(initial_value=f)
#sess.run(var)
init=tf.global_variables_initializer()
sess.run(init)
sess.run(var)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [12]:
ph=tf.placeholder(tf.float32,shape=(4,4),name="abdo")
ph

<tf.Tensor 'abdo:0' shape=(4, 4) dtype=float32>

In [13]:
a=tf.placeholder(dtype=tf.float32)
b=tf.placeholder(dtype=tf.float32)
res=a+b
with tf.Session() as sess:
    r=sess.run(res,feed_dict={a:5,b:6})

print(r)

11.0


In [23]:
import pandas as pd
diabetes=pd.read_csv('pima-indians-diabetes.csv')

In [24]:
diabetes.head()

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps   Insulin  \
0                6               0.743719        0.590164  0.353535  0.000000   
1                1               0.427136        0.540984  0.292929  0.000000   
2                8               0.919598        0.524590  0.000000  0.000000   
3                1               0.447236        0.540984  0.232323  0.111111   
4                0               0.688442        0.327869  0.353535  0.198582   

        BMI  Pedigree  Age  Class Group  
0  0.500745  0.234415   50      1     B  
1  0.396423  0.116567   31      0     C  
2  0.347243  0.253629   32      1     B  
3  0.418778  0.038002   21      0     B  
4  0.642325  0.943638   33      1     C

In [25]:
diabetes.columns

Index(['Number_pregnant', 'Glucose_concentration', 'Blood_pressure', 'Triceps',
       'Insulin', 'BMI', 'Pedigree', 'Age', 'Class', 'Group'],
      dtype='object')

In [26]:
col_norm=['Number_pregnant', 'Glucose_concentration', 'Blood_pressure', 'Triceps',
       'Insulin', 'BMI', 'Pedigree']
diabetes[col_norm]=diabetes[col_norm].apply(lambda x:(x-x.mean())/x.std())

In [27]:
diabetes.head()

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps   Insulin  \
0         0.639530               0.847771        0.149543  0.906679 -0.692439   
1        -0.844335              -1.122665       -0.160441  0.530556 -0.692439   
2         1.233077               1.942458       -0.263769 -1.287373 -0.692439   
3        -0.844335              -0.997558       -0.160441  0.154433  0.123221   
4        -1.141108               0.503727       -1.503707  0.906679  0.765337   

        BMI  Pedigree  Age  Class Group  
0  0.203880  0.468187   50      1     B  
1 -0.683976 -0.364823   31      0     C  
2 -1.102537  0.604004   32      1     B  
3 -0.493721 -0.920163   21      0     B  
4  1.408828  5.481337   33      1     C

In [28]:
n_p=tf.feature_column.numeric_column('Number_pregnant')
g_c=tf.feature_column.numeric_column('Glucose_concentration')
b_p=tf.feature_column.numeric_column('Blood_pressure')
t=tf.feature_column.numeric_column('Triceps')
i=tf.feature_column.numeric_column('Insulin')
b=tf.feature_column.numeric_column('BMI')
p=tf.feature_column.numeric_column('Pedigree')
a=tf.feature_column.numeric_column('Age')
assigned_group=tf.feature_column.categorical_column_with_vocabulary_list('group',['A','B','C','D'])



In [29]:
feat_cols=[n_p,g_c,b_p,t,i,b,p,a,assigned_group]


In [31]:
x_data=diabetes.drop('Class',axis=1)
labels=diabetes['Class']

In [32]:
from sklearn.model_selection import train_test_split


In [33]:
X_train, X_test, y_train, y_test = train_test_split(x_data,labels, test_size=0.3, random_state=42)

In [34]:
X_train

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps  \
334        -0.844335              -0.809897       -0.470426 -0.159003   
139         0.342757              -0.497129        0.149543  0.530556   
485        -1.141108               0.441173       -0.057113  1.345490   
547         0.045984               0.316066       -0.057113  0.029058   
18         -0.844335              -0.559683       -2.020348  1.094741   
..               ...                    ...             ...       ...   
71          0.342757               0.566280       -0.263769  0.906679   
106        -0.844335              -0.778620        2.732747 -1.287373   
270         1.826623              -0.622237        0.872840  1.032053   
435        -1.141108               0.628834       -3.570271 -1.287373   
102        -1.141108               0.128406        1.389481 -1.287373   

      Insulin       BMI  Pedigree  Age Group  
334 -0.189159 -1.026435 -0.639475   22     D  
139  2.127664  0.622441 -0.944308   28     D  
485  1.476871  1.307358 -0.322569   24     C  
547  0.747983  0.140462 -0.941290   28     D  
18   0.027772  1.434195 -0.871873   33     A  
..        ...       ...       ...  ...   ...  
71   0.522374 -0.430303 -0.183734   26     B  
106 -0.692439 -1.216690 -0.799437   27     A  
270 -0.692439  1.725919  2.004426   38     C  
435 -0.692439  1.320042 -0.805473   29     D  
102 -0.692439 -1.204006 -0.633439   21     A  

[537 rows x 9 columns]

In [35]:
X_test

Number_pregnant  Glucose_concentration  Blood_pressure   Triceps  \
668         0.639530              -0.716067       -0.573754  0.781305   
324        -0.547562              -0.278192        0.304536  0.718617   
624        -0.547562              -0.403299       -0.263769 -1.287373   
690         1.233077              -0.434576        0.562856 -1.287373   
473         0.936304               0.472450        1.079497 -1.287373   
..               ...                    ...             ...       ...   
619        -1.141108              -0.059255       -3.570271 -1.287373   
198         0.045984              -0.372022       -0.263769  1.470864   
538        -1.141108               0.190959        0.562856  1.032053   
329         0.639530              -0.497129        0.046215  0.718617   
302         0.342757              -1.372879        0.666184  1.282802   

      Insulin       BMI  Pedigree  Age Group  
668  0.956236  0.254615 -0.126389   43     A  
324 -0.692439  0.470237 -0.977508   21     C  
624 -0.692439 -0.151263 -0.947326   21     B  
690 -0.692439 -0.937649  1.159344   34     B  
473 -0.692439 -0.265415 -0.790382   50     D  
..        ...       ...       ...  ...   ...  
619 -0.692439  0.051676 -0.998635   24     D  
198  0.166608  0.356084  1.307233   26     D  
538  1.129781  0.546339  1.002400   23     B  
329 -0.102387 -0.151263 -1.055980   37     C  
302 -0.327995  0.482920 -0.953363   35     D  

[231 rows x 9 columns]

In [36]:
input_func=tf.estimator.inputs.pandas_input_fn(x=X_train,y=y_train,batch_size=10,num_epochs=1000,shuffle=True)
model=tf.estimator.LinearClassifier(feature_columns=feat_cols,n_classes=2)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\abdo\\AppData\\Local\\Temp\\tmpvn_ap61t', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000162A77A1978>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [37]:
model.train(input_fn=input_func,steps=1000)

INFO:tensorflow:Calling model_fn.


ValueError: Feature group is not in features dictionary.

In [2]:
mnist=input_data.read_data_sets("MNIST_data/",one_hot=True)


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [4]:
trainx=mnist.train.images
trainy=mnist.train.labels
trainx.shape

(55000, 784)

In [8]:
((trainX, trainY), (testX, testY)) = fashion_mnist.load_data()


In [9]:
trainX=trainX/255
testX=testX/255

In [9]:
plt.imshow(trainX[0],cmap='gray')
plt.show()
print(trainY[0])

NameError: name 'trainX' is not defined

In [24]:
trainX.shape
trainY.shape


(60000,)

In [20]:
trainX=tf.reshape(trainX,[trainX.shape[0],-1])


In [35]:
testX=tf.reshape(testX,[testX.shape[0],-1])


In [28]:
trainY=tf.one_hot(trainY,10)

In [21]:
trainX.shape

TensorShape([Dimension(60000), Dimension(784)])

In [4]:
x=tf.placeholder(tf.float32,shape=[None,784])
y_true=tf.placeholder(tf.float32,shape=[None,10])
w=tf.Variable(tf.zeros([784,10]))
b=tf.Variable(tf.zeros([10]))
y=tf.matmul(x,w)+b

In [5]:
cross_entropy=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true,logits=y))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [6]:
opt=tf.train.AdamOptimizer(learning_rate=0.5)
train=opt.minimize(cross_entropy)

In [7]:
init=tf.global_variables_initializer()

In [19]:
batch_size=50

In [22]:
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(10):
        ind=0
        for step in range(1000):
            x_mini_batch=trainx[ind:ind+batch_size]
            y_mini_batch=trainy[ind:ind+batch_size]
            sess.run(train,feed_dict={x:x_mini_batch,y_true:y_mini_batch})
            ind+=batch_size

        correct=tf.equal(tf.argmax(y,1),tf.argmax(y_true,1))
        acc=tf.reduce_mean(tf.cast(correct,tf.float32))
        print(sess.run(acc,feed_dict={x:trainx[0:1000],y_true:trainy[0:1000]}))
        
        
        

0.826
0.854
0.891
0.893
0.886
0.876
0.869
0.899
0.894
0.883


In [15]:
def init_weights(shape):
    init_rand=tf.truncated_normal(shape,stddev=0.1)
    return tf.Variable(init_rand)

In [16]:
def init_bias(shape):
    init_val=tf.constant(0.1,shape=shape)
    return tf.Variable(init_val)

In [17]:
def conv2d(x,w):
    return tf.nn.conv2d(x,w,strides=[1,1,1,1],padding='SAME')
    

In [18]:
def max_pool_2by2(x):
    return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding='SAME')
    

In [19]:
def convolutional_layer(input_x,shape):
    w=init_weights(shape)
    b=init_bias([shape[3]])
    return tf.nn.relu(conv2d(input_x,w)+b)
    

In [23]:
def normal_full_layer(input_layer,size):
    input_size=int(input_layer.get_shape()[1])
    w=init_weights([input_size,size])
    b=init_bias([size])
    return tf.matmul(input_layer,w)+b

In [24]:
x=tf.placeholder(tf.float32,shape=[None,784])
image_x=tf.reshape(x,[-1,28,28,1])
y_true=tf.placeholder(tf.float32,shape=[None,10])


In [25]:
convo_1=convolutional_layer(image_x,[5,5,1,32])
max_pool_1=max_pool_2by2(convo_1)

convo_2=convolutional_layer(max_pool_1,[5,5,32,64])
max_pool_2=max_pool_2by2(convo_2)

flatten_layer=tf.reshape(max_pool_2,shape=[-1,7*7*64])
fully_layer_one=tf.nn.relu(normal_full_layer(flatten_layer,1024))

hold_prob=tf.placeholder(tf.float32)
drop_out=tf.nn.dropout(fully_layer_one,keep_prob=hold_prob)
y_pred=normal_full_layer(drop_out,10)



In [26]:
cross_entropy=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true,logits=y_pred))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [27]:
opt=tf.train.AdamOptimizer(learning_rate=0.001)
train=opt.minimize(cross_entropy)

In [28]:
init=tf.global_variables_initializer()

In [ ]:
epochs=5000
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(epochs):
        
        x_mini_batch,y_mini_batch=mnist.train.next_batch(50)
        sess.run(train,feed_dict={x:x_mini_batch,y_true:y_mini_batch,hold_prob:0.5})
        if epoch%100==0:

            correct=tf.equal(tf.argmax(y_pred,1),tf.argmax(y_true,1))
            acc=tf.reduce_mean(tf.cast(correct,tf.float32))
            print(sess.run(acc,feed_dict={x:trainx[0:1000],y_true:trainy[0:1000]}))
        